name: gg_golden
description: gg_golden implements a way to manage relational data in JSON.
version: 3.0.0
repository: https://github.com/ggsuite/gg_golden.git

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  collection: ^1.19.1
  path: ^1.8.0
  test: ^1.24.0

dev_dependencies:
  lints: ^6.0.0
